package reify

import (
	"fmt"
	"go/format"
	"os"
	"strings"

	"github.com/mirandaguillaume/reify/pkg/model"
)

// nodeEmission describes a single DAG node to emit — either a skill node or a merge node.
type nodeEmission struct {
	skill     *model.SkillBehavior
	renames   map[string]string // original type → renamed type (parallel duplicates)
	isMerge   bool
	mergeType string   // original type name
	mergeVars []string // renamed variant names to merge
}

// buildEmissions converts an agent's stage/skill list into an ordered []nodeEmission,
// inserting merge nodes after parallel stages where multiple skills produce the same type.
func buildEmissions(agent model.AgentComposition, skillMap map[string]model.SkillBehavior) []nodeEmission {
	var emissions []nodeEmission

	emitSkill := func(name string, renames map[string]string) {
		s, ok := skillMap[name]
		if !ok {
			return
		}
		sc := s
		emissions = append(emissions, nodeEmission{skill: &sc, renames: renames})
	}

	if len(agent.Stages) > 0 {
		for _, stage := range agent.Stages {
			if stage.Strategy == model.OrchestrationParallel {
				// Count how many skills in this stage produce each type.
				typeCount := map[string]int{}
				for _, name := range stage.Skills {
					if s, ok := skillMap[name]; ok {
						for _, p := range s.Context.Produces {
							typeCount[p]++
						}
					}
				}
				// Assign per-skill renames for duplicated types.
				mergeMap := map[string][]string{} // origType → variant names
				for _, name := range stage.Skills {
					renames := map[string]string{}
					if s, ok := skillMap[name]; ok {
						for _, p := range s.Context.Produces {
							if typeCount[p] > 1 {
								safeID := strings.NewReplacer("-", "_", ".", "_").Replace(name)
								renamed := p + "__" + safeID
								renames[p] = renamed
								mergeMap[p] = append(mergeMap[p], renamed)
							}
						}
					}
					emitSkill(name, renames)
				}
				// One merge node per duplicated type.
				for origType, variants := range mergeMap {
					emissions = append(emissions, nodeEmission{
						isMerge:   true,
						mergeType: origType,
						mergeVars: variants,
					})
				}
			} else {
				for _, name := range stage.Skills {
					emitSkill(name, nil)
				}
			}
		}
	} else {
		for _, s := range agent.AllSkills() {
			emitSkill(s, nil)
		}
	}
	return emissions
}

// GenerateAgentGo generates a complete Go main.go program for an agent's DAG runtime.
func GenerateAgentGo(agent model.AgentComposition, skills []model.SkillBehavior) string {
	var b strings.Builder

	skillMap := map[string]model.SkillBehavior{}
	for _, s := range skills {
		skillMap[s.Skill] = s
	}

	// Collect all consumed types across skills that have no internal producer
	allProduced := map[string]bool{}
	for _, s := range skills {
		for _, p := range s.Context.Produces {
			allProduced[p] = true
		}
	}
	externalInputs := []string{}
	seen := map[string]bool{}
	for _, s := range skills {
		for _, c := range s.Context.Consumes {
			if !allProduced[c] && !seen[c] {
				externalInputs = append(externalInputs, c)
				seen[c] = true
			}
		}
	}

	// Agent header comment + package declaration
	fmt.Fprintf(&b, "// Generated by reify for agent: %s\n\n", agent.Agent)
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"bytes\"\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"flag\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"io\"\n")
	b.WriteString("\t\"net/http\"\n")
	b.WriteString("\t\"os\"\n")
	b.WriteString("\t\"os/exec\"\n")
	b.WriteString("\t\"path/filepath\"\n")
	b.WriteString("\t\"strings\"\n")
	b.WriteString("\t\"time\"\n\n")
	b.WriteString("\t\"github.com/mirandaguillaume/reify/pkg/dag\"\n")
	b.WriteString(")\n\n")

	// main function
	b.WriteString("func main() {\n")
	// Flags
	b.WriteString("\tvar inputFlags multiFlag\n")
	b.WriteString("\toutputDir := flag.String(\"output\", \"\", \"directory to write output files (one per produced type)\")\n")
	b.WriteString("\tflag.Var(&inputFlags, \"input\", \"key=value or key=@file.txt (repeatable)\")\n")
	b.WriteString("\tflag.Parse()\n\n")
	// Provider
	b.WriteString("\tvar provider llmProvider\n")
	b.WriteString("\tif key := os.Getenv(\"OPENROUTER_API_KEY\"); key != \"\" {\n")
	b.WriteString("\t\tmodel := os.Getenv(\"OPENROUTER_MODEL\")\n")
	b.WriteString("\t\tif model == \"\" {\n")
	b.WriteString("\t\t\tmodel = \"anthropic/claude-3.5-haiku\"\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tprovider = newOpenRouterProvider(key, model)\n")
	b.WriteString("\t} else if key := os.Getenv(\"ANTHROPIC_API_KEY\"); key != \"\" {\n")
	b.WriteString("\t\tprovider = newAnthropicProvider(key)\n")
	b.WriteString("\t} else {\n")
	b.WriteString("\t\tfmt.Fprintln(os.Stderr, \"OPENROUTER_API_KEY or ANTHROPIC_API_KEY is required\")\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n\n")

	// Nodes
	emissions := buildEmissions(agent, skillMap)
	b.WriteString("\tnodes := []*dag.Node{\n")
	for _, e := range emissions {
		if e.isMerge {
			// Merge node: concatenates all variant outputs into the original type.
			mergeID := "merge__" + strings.ReplaceAll(e.mergeType, "-", "_")
			b.WriteString("\t\t{\n")
			fmt.Fprintf(&b, "\t\t\tID: %q,\n", mergeID)
			consumeStrs := make([]string, len(e.mergeVars))
			for i, v := range e.mergeVars {
				consumeStrs[i] = fmt.Sprintf("%q", v)
			}
			fmt.Fprintf(&b, "\t\t\tConsumes: []string{%s},\n", strings.Join(consumeStrs, ", "))
			fmt.Fprintf(&b, "\t\t\tProduces: []string{%q},\n", e.mergeType)
			fmt.Fprintf(&b, "\t\t\tMaxRetries: %d,\n", 0)
			fmt.Fprintf(&b, "\t\t\tTimeout:    time.Duration(%d),\n", 0)
			// Inline Run closure that joins all variants.
			b.WriteString("\t\t\tRun: func(ctx context.Context, inputs map[string]any) (map[string]any, error) {\n")
			b.WriteString("\t\t\t\tvar parts []string\n")
			for _, v := range e.mergeVars {
				fmt.Fprintf(&b, "\t\t\t\tif v, ok := inputs[%q]; ok {\n", v)
				fmt.Fprintf(&b, "\t\t\t\t\tparts = append(parts, fmt.Sprintf(\"=== %s ===\\n%%v\", v))\n", v)
				b.WriteString("\t\t\t\t}\n")
			}
			fmt.Fprintf(&b, "\t\t\t\treturn map[string]any{%q: strings.Join(parts, \"\\n\\n\")}, nil\n", e.mergeType)
			b.WriteString("\t\t\t},\n")
			b.WriteString("\t\t},\n")
			continue
		}

		s := *e.skill
		prompt := BuildPromptTemplate(s)
		escapedPrompt := strings.ReplaceAll(prompt, "`", "` + \"`\" + `")

		// Apply renames to produces list.
		produces := make([]string, len(s.Context.Produces))
		for i, p := range s.Context.Produces {
			if renamed, ok := e.renames[p]; ok {
				produces[i] = renamed
			} else {
				produces[i] = p
			}
		}

		b.WriteString("\t\t{\n")
		fmt.Fprintf(&b, "\t\t\tID: %q,\n", s.Skill)

		// Consumes
		if len(s.Context.Consumes) > 0 {
			consumeStrs := make([]string, len(s.Context.Consumes))
			for i, c := range s.Context.Consumes {
				consumeStrs[i] = fmt.Sprintf("%q", c)
			}
			fmt.Fprintf(&b, "\t\t\tConsumes: []string{%s},\n", strings.Join(consumeStrs, ", "))
		}

		// Produces (potentially renamed)
		if len(produces) > 0 {
			produceStrs := make([]string, len(produces))
			for i, p := range produces {
				produceStrs[i] = fmt.Sprintf("%q", p)
			}
			fmt.Fprintf(&b, "\t\t\tProduces: []string{%s},\n", strings.Join(produceStrs, ", "))
		}

		// Retry / timeout (defaults: 0)
		fmt.Fprintf(&b, "\t\t\tMaxRetries: %d,\n", 0)
		fmt.Fprintf(&b, "\t\t\tTimeout:    time.Duration(%d),\n", 0)

		// Run function — use renamed produces for output keys.
		fmt.Fprintf(&b, "\t\t\tRun: makeSkillRunner(provider, `%s`, []string{", escapedPrompt)
		for i, p := range produces {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%q", p)
		}
		b.WriteString("}),\n")
		b.WriteString("\t\t},\n")
	}
	b.WriteString("\t}\n\n")

	// Build and execute DAG
	b.WriteString("\td, err := dag.New(nodes...)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"DAG error: %v\\n\", err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n\n")

	// Discover inputs then apply --input flag overrides
	fmt.Fprintf(&b, "\tinputs := discoverInputs([]string{%s})\n", joinQuoted(externalInputs))
	b.WriteString("\tfor _, kv := range inputFlags {\n")
	b.WriteString("\t\tk, v := parseInputFlag(kv)\n")
	b.WriteString("\t\tif k != \"\" {\n")
	b.WriteString("\t\t\tinputs[k] = v\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n\n")

	b.WriteString("\tresults, err := d.Execute(context.Background(), dag.WithInputs(inputs))\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"Execution error: %v\\n\", err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n\n")
	// Output to files or stdout
	b.WriteString("\tfor k, v := range results {\n")
	b.WriteString("\t\tcontent := fmt.Sprintf(\"%v\", v)\n")
	b.WriteString("\t\tif *outputDir != \"\" {\n")
	b.WriteString("\t\t\tif err := os.MkdirAll(*outputDir, 0755); err != nil {\n")
	b.WriteString("\t\t\t\tfmt.Fprintf(os.Stderr, \"mkdir %s: %v\\n\", *outputDir, err)\n")
	b.WriteString("\t\t\t\tcontinue\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tpath := filepath.Join(*outputDir, k+\".md\")\n")
	b.WriteString("\t\t\tif err := os.WriteFile(path, []byte(content), 0644); err != nil {\n")
	b.WriteString("\t\t\t\tfmt.Fprintf(os.Stderr, \"write %s: %v\\n\", path, err)\n")
	b.WriteString("\t\t\t} else {\n")
	b.WriteString("\t\t\t\tfmt.Printf(\"wrote %s\\n\", path)\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t} else {\n")
	b.WriteString("\t\t\tfmt.Printf(\"=== %s ===\\n%s\\n\\n\", k, content)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	// makeSkillRunner helper
	b.WriteString(makeSkillRunnerCode())

	// discoverInputs helper
	b.WriteString(discoverInputsCode())

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "warning: generated code failed gofmt: %v\n", err)
		return b.String()
	}
	return string(formatted)
}

// GenerateGoMod generates a go.mod file for the generated runtime.
func GenerateGoMod(agentName string) string {
	safeName := strings.ToLower(strings.ReplaceAll(agentName, " ", "-"))
	var b strings.Builder
	fmt.Fprintf(&b, "module %s\n\n", safeName)
	b.WriteString("go 1.22\n\n")
	b.WriteString("require github.com/mirandaguillaume/reify v0.0.0\n\n")
	b.WriteString("replace github.com/mirandaguillaume/reify => ../..\n")
	return b.String()
}

func joinQuoted(items []string) string {
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(quoted, ", ")
}

func makeSkillRunnerCode() string {
	return `// llmProvider abstracts an LLM backend for text completion.
type llmProvider interface {
	Complete(ctx context.Context, prompt string) (string, error)
}

// anthropicProvider calls the Anthropic Messages API.
type anthropicProvider struct {
	apiKey string
}

func newAnthropicProvider(apiKey string) *anthropicProvider {
	return &anthropicProvider{apiKey: apiKey}
}

type anthropicRequest struct {
	Model     string             ` + "`" + `json:"model"` + "`" + `
	MaxTokens int                ` + "`" + `json:"max_tokens"` + "`" + `
	Messages  []anthropicMessage ` + "`" + `json:"messages"` + "`" + `
}

type anthropicMessage struct {
	Role    string ` + "`" + `json:"role"` + "`" + `
	Content string ` + "`" + `json:"content"` + "`" + `
}

type anthropicResponse struct {
	Content []anthropicContent ` + "`" + `json:"content"` + "`" + `
	Error   *struct {
		Message string ` + "`" + `json:"message"` + "`" + `
	} ` + "`" + `json:"error,omitempty"` + "`" + `
}

type anthropicContent struct {
	Type string ` + "`" + `json:"type"` + "`" + `
	Text string ` + "`" + `json:"text"` + "`" + `
}

// openRouterProvider calls the OpenRouter API (OpenAI-compatible).
type openRouterProvider struct {
	apiKey string
	model  string
}

func newOpenRouterProvider(apiKey, model string) *openRouterProvider {
	return &openRouterProvider{apiKey: apiKey, model: model}
}

type openRouterRequest struct {
	Model    string              ` + "`" + `json:"model"` + "`" + `
	Messages []anthropicMessage  ` + "`" + `json:"messages"` + "`" + `
}

type openRouterResponse struct {
	Choices []struct {
		Message struct {
			Content string ` + "`" + `json:"content"` + "`" + `
		} ` + "`" + `json:"message"` + "`" + `
	} ` + "`" + `json:"choices"` + "`" + `
	Error *struct {
		Message string ` + "`" + `json:"message"` + "`" + `
	} ` + "`" + `json:"error,omitempty"` + "`" + `
}

// NOTE: ctx is forwarded to the HTTP request for cancellation support
func (p *openRouterProvider) Complete(ctx context.Context, prompt string) (string, error) {
	reqBody := openRouterRequest{
		Model:    p.model,
		Messages: []anthropicMessage{{Role: "user", Content: prompt}},
	}
	body, err := json.Marshal(reqBody)
	if err != nil {
		return "", fmt.Errorf("marshal request: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, "POST", "https://openrouter.ai/api/v1/chat/completions", bytes.NewReader(body))
	if err != nil {
		return "", fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+p.apiKey)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("send request: %w", err)
	}
	defer resp.Body.Close()
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("read response: %w", err)
	}
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("API error %d: %s", resp.StatusCode, string(respBody))
	}
	var result openRouterResponse
	if err := json.Unmarshal(respBody, &result); err != nil {
		return "", fmt.Errorf("unmarshal response: %w", err)
	}
	if result.Error != nil {
		return "", fmt.Errorf("API error: %s", result.Error.Message)
	}
	if len(result.Choices) == 0 {
		return "", fmt.Errorf("empty response from API")
	}
	return result.Choices[0].Message.Content, nil
}

// NOTE: ctx is forwarded to the HTTP request for cancellation support
func (p *anthropicProvider) Complete(ctx context.Context, prompt string) (string, error) {
	reqBody := anthropicRequest{
		Model:     "claude-sonnet-4-20250514",
		MaxTokens: 8192,
		Messages:  []anthropicMessage{{Role: "user", Content: prompt}},
	}
	body, err := json.Marshal(reqBody)
	if err != nil {
		return "", fmt.Errorf("marshal request: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, "POST", "https://api.anthropic.com/v1/messages", bytes.NewReader(body))
	if err != nil {
		return "", fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-api-key", p.apiKey)
	req.Header.Set("anthropic-version", "2023-06-01")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("send request: %w", err)
	}
	defer resp.Body.Close()
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("read response: %w", err)
	}
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("API error %d: %s", resp.StatusCode, string(respBody))
	}
	var result anthropicResponse
	if err := json.Unmarshal(respBody, &result); err != nil {
		return "", fmt.Errorf("unmarshal response: %w", err)
	}
	if result.Error != nil {
		return "", fmt.Errorf("API error: %s", result.Error.Message)
	}
	if len(result.Content) == 0 {
		return "", fmt.Errorf("empty response from API")
	}
	return result.Content[0].Text, nil
}

func makeSkillRunner(
	provider llmProvider,
	promptTemplate string,
	produces []string,
) func(context.Context, map[string]any) (map[string]any, error) {
	return func(ctx context.Context, inputs map[string]any) (map[string]any, error) {
		prompt := promptTemplate
		for k, v := range inputs {
			prompt = strings.ReplaceAll(prompt, "{{ ."+k+" }}", fmt.Sprintf("%v", v))
		}
		response, err := provider.Complete(ctx, prompt)
		if err != nil {
			return nil, err
		}
		out := make(map[string]any, len(produces))
		for _, p := range produces {
			out[p] = response
		}
		return out, nil
	}
}

`
}

func discoverInputsCode() string {
	return `// multiFlag allows --input to be specified multiple times.
type multiFlag []string

func (f *multiFlag) String() string { return strings.Join(*f, ", ") }
func (f *multiFlag) Set(v string) error {
	*f = append(*f, v)
	return nil
}

// parseInputFlag parses "key=value" or "key=@file.txt" into (key, content).
func parseInputFlag(kv string) (string, string) {
	idx := strings.IndexByte(kv, '=')
	if idx < 0 {
		return "", ""
	}
	k, v := kv[:idx], kv[idx+1:]
	if strings.HasPrefix(v, "@") {
		data, err := os.ReadFile(v[1:])
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: cannot read input file %s: %v\n", v[1:], err)
			return k, ""
		}
		return k, string(data)
	}
	return k, v
}

func discoverInputs(needed []string) map[string]any {
	inputs := make(map[string]any)
	for _, key := range needed {
		switch key {
		case "git_diff":
			if out, err := exec.Command("git", "diff", "HEAD").Output(); err == nil {
				inputs[key] = string(out)
			}
		case "file_tree":
			if out, err := exec.Command("git", "ls-files").Output(); err == nil {
				inputs[key] = string(out)
			}
		case "source_code":
			if out, err := exec.Command("git", "ls-files").Output(); err == nil {
				files := strings.Split(strings.TrimSpace(string(out)), "\n")
				var sb strings.Builder
				for _, f := range files {
					if content, err := os.ReadFile(f); err == nil {
						fmt.Fprintf(&sb, "=== %s ===\n%s\n", f, string(content))
						if sb.Len() > 100000 {
							break
						}
					}
				}
				inputs[key] = sb.String()
			}
		case "pr_diff":
			if out, err := exec.Command("gh", "pr", "diff").Output(); err == nil {
				inputs[key] = string(out)
			}
		case "pr_url":
			if out, err := exec.Command("gh", "pr", "view", "--json", "url", "-q", ".url").Output(); err == nil {
				inputs[key] = strings.TrimSpace(string(out))
			}
		case "code_analysis":
			// code_analysis is computed externally (by CLI or bench) and passed via --input.
			// If not provided but git_diff is available, leave empty — the caller should provide it.
		}
	}
	return inputs
}
`
}
